### ISSUE TITLE
Sass support

### ISSUE THREAD

**Issue by ezekg** [electronjs/electron-compilers#20]
It looks like Sass used to be supported, but isn't any longer. Is there a reason as to why? Would you be open to pull requests to reimplement it?

**Comment by anaisbetts** [comment]
@ezekg node-sass caused too many problems, it didn't build correctly for Electron and would break the Linux build (even if you weren't using it!)  If it can be fixed that'd be amazing but I'm not optimistic

**Comment by asdine** [comment]
What about using [postcss](https://github.com/postcss/postcss) with [precss](https://github.com/jonathantneal/precss) ?

**Comment by malept** [comment]
It would probably be worth switching to https://www.npmjs.com/package/dart-sass once it's out of alpha.

**Comment by anaisbetts** [comment]
Sass is now added back via sass.js, but has some issues. It might work for you though!
