### ISSUE TITLE
Stylus support?

### ISSUE THREAD

**Issue by jamen** [electronjs/electron-compilers#33]
I use Stylus primarily.  Stylus is made in JavaScript, so it should be okay.

**Comment by anaisbetts** [comment]
Sure, I'd take a PR for it

**Comment by anaisbetts** [comment]
Submit a PR to this repo for the compiler, then submit a PR to electron-compile to add some tests, use `npm link` to pull it in. If that makes no sense, let me know and I can help out :)

**Comment by lellimecnar** [comment]
I was just playing around with this today, but I must be missing something... I've created a new class in `src/css/stylus.js` which extends the `SimpleCompilerBase` class, set up the `compileSync()` method, and then I added the mime type and extension to `rig-mime-types.js` in the other repo. I added some logs to make sure it was getting into the new class constructor, which it is, but it's never getting into the `compileSync` method...

What am I missing?

**Comment by anaisbetts** [comment]
@lellimecnar Send up what you've got as PRs and I'll have a look, it sounds like you're on the right track

**Comment by lellimecnar** [comment]
@paulcbetts #36 
let me know if I should create a pr for the changes to the other repo as well

**Comment by anaisbetts** [comment]
@lellimecnar Please do!

**Comment by lellimecnar** [comment]
I manually updated `db.json` in `mime-db` to include the stylus mime type, and it's at least compiling. For whatever reason, modifying `rig-mime-types.js` wasn't enough.

I'm assuming there was a reason for using a scoped version of `mime-db`? Can that be updated?

**Comment by anaisbetts** [comment]
@lellimecnar Yeah, the scoped version is intentional because the original `mime-db` takes up a ton of memory

**Comment by lellimecnar** [comment]
So, since we're only working with a handful of mime types, can we just forgo the module altogether, and use the file extension instead? Since that's really all the module is doing anyway...

**Comment by anaisbetts** [comment]
@lellimecnar I actually just got it working with the custom mime-db, my big problem right now is that Stylus only offers an async API, which only _happens_ to work for compileSync atm, it's not guaranteed to (because stylus could choose to call the `fn` later)

**Comment by anaisbetts** [comment]
Added in 3.2.0!

**Comment by jamen** [comment]
Awesome, thanks @lellimecnar and @paulcbetts.
