### ISSUE TITLE
Not found : @paulcbetts/node-sass

### ISSUE THREAD

**Issue by peteroome** [electronjs/electron-compilers#44]
Hi, i'm getting `Not found : @paulcbetts/node-sass` when running `npm install electron-compilers --save-dev`. Did `@paulcbetts/node-sass` get unpublished or something? Or am i doing something wrong?

Thanks for your help.

**Comment by MarshallOfSound** [comment]
For reference

https://github.com/electron-userland/electron-forge/issues/37

**Comment by mrsimonemms** [comment]
If you are stuck whilst waiting for a fix, add the following `npm-shrinkwrap.json` to the root of your project

```json
{
  "name": "NodeDB",
  "version": "0.0.0",
  "dependencies": {
    "electron-compilers": {
      "version": "4.0.7"
    }
  }
}
```

**Comment by anaisbetts** [comment]
Sorry about that all, package was marked as private somehow

**Comment by mrsimonemms** [comment]
Thanks @paulcbetts and merry Christmas

**Comment by peteroome** [comment]
Thanks @paulcbetts. And thanks for the suggestion @riggerthegeek. 👌
